from typing import Any
from typing import Optional
from typing import overload

class Marker:
    @overload
    def evaluate(self) -> bool: ...
    @overload
    def evaluate(self, environment: Optional[Any]) -> bool: ...
    _markers: Any

class Node: ...
class Variable(Node): ...
class Op(Node): ...
class Value(Node): ...
