from typing import Any
from typing import Dict
from typing import Optional

class Marker:
    def evaluate(self, environment: Optional[Dict[str, Any]] = ...) -> bool: ...
    _markers: Any

class Node: ...
class Variable(Node): ...
class Op(Node): ...
class Value(Node): ...

def default_environment() -> Dict[str, Any]: ...
