# DO NOT EDIT THIS FILE!
#
# Nix expressions autogenerated with:
#   bin/pypi2nix -n sentryPackages -d sentry -i setuptools -p sentry/5.4.5.txt -o sentry/5.4.5.nix

{ pkgs, pythonPackages }:

let sentryPackages = pythonPackages.python.modules // rec {
  inherit (pythonPackages) buildPythonPackage setuptools;
  inherit (pkgs) fetchurl stdenv;

  sentry = buildPythonPackage rec {
    name = "sentry-5.4.5";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/s/sentry/sentry-5.4.5.tar.gz";
      md5 = "8c92260cc2b956edf8340b5634ba0b08";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ celery django_static_compiler django_celery django nydus django_social_auth_trello cssutils django_indexer django_paging beautifulsoup django_crispy_forms simplejson logan python_dateutil redis django_picklefield raven pynliner gunicorn httpagentparser south pygments setproctitle django_social_auth django_templatetag_sugar ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  setproctitle = buildPythonPackage rec {
    name = "setproctitle-1.1.7";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/s/setproctitle/setproctitle-1.1.7.zip";
      md5 = "e89a27ed9c355d4849f2522b293e2129";
    };
    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  pynliner = buildPythonPackage rec {
    name = "pynliner-0.4.0";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/pynliner/pynliner-0.4.0.tar.gz";
      md5 = "554b9cacabf06b5817c505979145f56d";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  cssutils = buildPythonPackage rec {
    name = "cssutils-0.9.10";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/c/cssutils/cssutils-0.9.10.zip";
      md5 = "81b5c0294c54479a54548769eaa236f8";
    };
    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  logan = buildPythonPackage rec {
    name = "logan-0.5.5";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/l/logan/logan-0.5.5.tar.gz";
      md5 = "3e0126a45d80abde269339e1ab6a19c6";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  pygments = buildPythonPackage rec {
    name = "Pygments-1.6";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/P/Pygments/Pygments-1.6.tar.gz";
      md5 = "a18feedf6ffd0b0cc8c8b0fbdb2027b1";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  amqp = buildPythonPackage rec {
    name = "amqp-1.0.11";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/a/amqp/amqp-1.0.11.tar.gz";
      md5 = "0c09b0ec8a042e8b29f4b7044d91af40";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_static_compiler = buildPythonPackage rec {
    name = "django-static-compiler-0.3.1";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-static-compiler/django-static-compiler-0.3.1.tar.gz";
      md5 = "821c02e3cd5ace56fb0d6a155c5453a0";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ django ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  six = buildPythonPackage rec {
    name = "six-1.3.0";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/s/six/six-1.3.0.tar.gz";
      md5 = "ec47fe6070a8a64c802363d2c2b1e2ee";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  redis = buildPythonPackage rec {
    name = "redis-2.7.2";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/r/redis/redis-2.7.2.tar.gz";
      md5 = "17ac60dcf13eb33f82cc25974ab17157";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  beautifulsoup = buildPythonPackage rec {
    name = "BeautifulSoup-3.2.1";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/B/BeautifulSoup/BeautifulSoup-3.2.1.tar.gz";
      md5 = "44656527ef3ac9874ac4d1c9f35f70ee";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  celery = buildPythonPackage rec {
    name = "celery-3.0.18";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/c/celery/celery-3.0.18.tar.gz";
      md5 = "ca1a7027e229c9cc99a16d9852cebc3e";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ billiard python_dateutil kombu ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  kombu = buildPythonPackage rec {
    name = "kombu-2.5.10";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/k/kombu/kombu-2.5.10.tar.gz";
      md5 = "cc9845f65774b82f62e97203a2eee18a";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ amqp anyjson ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  python_dateutil = buildPythonPackage rec {
    name = "python-dateutil-1.5";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-1.5.tar.gz";
      md5 = "0dcb1de5e5cad69490a3b6ab63f0cfa5";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_social_auth_trello = buildPythonPackage rec {
    name = "django-social-auth-trello-1.0.3";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-social-auth-trello/django-social-auth-trello-1.0.3.tar.gz";
      md5 = "71eec6f84bad80c366fccc5a682d061a";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ django_social_auth ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  raven = buildPythonPackage rec {
    name = "raven-3.3.3";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/r/raven/raven-3.3.3.tar.gz";
      md5 = "e8930777ad7d9a8a7f14e06a4087d653";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  gunicorn = buildPythonPackage rec {
    name = "gunicorn-0.17.2";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/g/gunicorn/gunicorn-0.17.2.tar.gz";
      md5 = "4f4cdd0ad0fd864eb9abd9d6a4ea931e";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  simplejson = buildPythonPackage rec {
    name = "simplejson-3.1.3";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/s/simplejson/simplejson-3.1.3.tar.gz";
      md5 = "ffb9fdd8ff3225a61b455bb1bcb98e41";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  pytz = buildPythonPackage rec {
    name = "pytz-2013b";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/pytz/pytz-2013b.zip";
      md5 = "c70dc37ffe435dd77e3f967a0dffe928";
    };
    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  httplib2 = buildPythonPackage rec {
    name = "httplib2-0.8";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/h/httplib2/httplib2-0.8.zip";
      md5 = "c92df9674a18f2b6e20ff2c5b7ada579";
    };
    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_picklefield = buildPythonPackage rec {
    name = "django-picklefield-0.3.0";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-picklefield/django-picklefield-0.3.0.tar.gz";
      md5 = "9b5eb60e03c6a5c3d0939fa448cae8b2";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ six ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_templatetag_sugar = buildPythonPackage rec {
    name = "django-templatetag-sugar-0.1";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-templatetag-sugar/django-templatetag-sugar-0.1.tar.gz";
      md5 = "f5b8bf6e4cb82f8affa761574bf3dae4";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_crispy_forms = buildPythonPackage rec {
    name = "django-crispy-forms-1.2.4";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-crispy-forms/django-crispy-forms-1.2.4.tar.gz";
      md5 = "aa6ffebe6d9b4cc59f64e2b5be27cf74";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  oauth2 = buildPythonPackage rec {
    name = "oauth2-1.5.211";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.211.tar.gz";
      md5 = "987ad7365a70e2286bd1cebb344debbc";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ httplib2 ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_indexer = buildPythonPackage rec {
    name = "django-indexer-0.3.0";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-indexer/django-indexer-0.3.0.tar.gz";
      md5 = "3e10959319901d5f27d356bdd377b0cb";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_paging = buildPythonPackage rec {
    name = "django-paging-0.2.4";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-paging/django-paging-0.2.4.tar.gz";
      md5 = "1eac7bed6921509492852dd99937b5d9";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ django_templatetag_sugar ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django = buildPythonPackage rec {
    name = "Django-1.4.5";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/D/Django/Django-1.4.5.tar.gz";
      md5 = "851d00905eb70e4aa6384b3b8b111fb7";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  nydus = buildPythonPackage rec {
    name = "nydus-0.10.5";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/n/nydus/nydus-0.10.5.tar.gz";
      md5 = "ee6d383f15f60bc9983b7e390dc4402b";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_social_auth = buildPythonPackage rec {
    name = "django-social-auth-0.7.22";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-social-auth/django-social-auth-0.7.22.tar.gz";
      md5 = "1f6750781c6d217b69f932376dbba62c";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ oauth2 django python_openid ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  billiard = buildPythonPackage rec {
    name = "billiard-2.7.3.28";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/b/billiard/billiard-2.7.3.28.tar.gz";
      md5 = "a9ec91b43a40b52ce2d096c2263cb98d";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  httpagentparser = buildPythonPackage rec {
    name = "httpagentparser-1.2.2";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/h/httpagentparser/httpagentparser-1.2.2.tar.gz";
      md5 = "5e2e43769bf81d959484576f8dabaae4";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  python_openid = buildPythonPackage rec {
    name = "python-openid-2.2.5";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/python-openid/python-openid-2.2.5.zip";
      md5 = "f89d9d4f4dccfd33b5ce34eb4725f751";
    };
    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  anyjson = buildPythonPackage rec {
    name = "anyjson-0.3.3";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/a/anyjson/anyjson-0.3.3.tar.gz";
      md5 = "2ea28d6ec311aeeebaf993cb3008b27c";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  south = buildPythonPackage rec {
    name = "South-0.7.6";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/S/South/South-0.7.6.tar.gz";
      md5 = "6089871449006d45d06c409b42d8bd44";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

  django_celery = buildPythonPackage rec {
    name = "django-celery-3.0.17";
    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/django-celery/django-celery-3.0.17.tar.gz";
      md5 = "5be52b20ee3c7b1a28a2949ae87029c9";
    };
    buildInputs = [  ];
    propagatedBuildInputs = [ celery pytz ];
    doCheck = false;
    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';
    
    meta = {
      description = "UNKNOWN";
      homepage = "UNKNOWN";
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
    };
  };

}; in sentryPackages
