# DO NOT EDIT THIS FILE!
#
# Nix expressions autogenerated with:
#   bin/pypi2nix-nalmir01Packages-dalmir-isetuptools-ealmir/01.json-palmir/01.txt-oalmir/01.nix

{ pkgs, python, pythonPackages }:

let almir01Packages = python.modules // rec {
  inherit python;
  inherit (pythonPackages) setuptools buildPythonPackage;
  inherit (pkgs) fetchurl stdenv;

  pyramid = buildPythonPackage rec {
    name = "pyramid-1.3.4";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/pyramid/pyramid-1.3.4.tar.gz";
      md5 = "967a04fcb2143b31b279c3013a778a2b";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ venusian translationstring repoze_lru mako pastedeploy webob zope_interface setuptools chameleon zope_deprecation ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  pyramid_exclog = buildPythonPackage rec {
    name = "pyramid_exclog-0.5";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/pyramid_exclog/pyramid_exclog-0.5.tar.gz";
      md5 = "09b45c82b845ba7b552bef239d93b4f1";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ pyramid ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  almir = buildPythonPackage rec {
    name = "almir-0.1.7";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/a/almir/almir-0.1.7.zip";
      md5 = "daea15c898487a2bded1ae6ef78633e5";
    };

    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [ pyramid_tm pyramid zope_sqlalchemy pyramid_exclog pytz webhelpers mysql_connector_repackaged pyramid_beaker colander docutils transaction deform_bootstrap pg8000 sqlalchemy pyramid_jinja2 waitress deform ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  zope_sqlalchemy = buildPythonPackage rec {
    name = "zope.sqlalchemy-0.7.2";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/z/zope.sqlalchemy/zope.sqlalchemy-0.7.2.zip";
      md5 = "b654e5d144ed141e13b42591a21a4868";
    };

    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [ sqlalchemy transaction zope_interface setuptools ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  sqlalchemy = buildPythonPackage rec {
    name = "SQLAlchemy-0.7.6";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/S/SQLAlchemy/SQLAlchemy-0.7.6.tar.gz";
      md5 = "6383cade61ecff1a236708fae066447a";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  deform = buildPythonPackage rec {
    name = "deform-0.9.4";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/deform/deform-0.9.4.tar.gz";
      md5 = "2ed7b69644a6d8f4e1404e1892329240";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ peppercorn colander translationstring chameleon ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  mako = buildPythonPackage rec {
    name = "Mako-0.6.2";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/M/Mako/Mako-0.6.2.tar.gz";
      md5 = "b467eb01c2227e205784faa3bef96725";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ markupsafe ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  repoze_lru = buildPythonPackage rec {
    name = "repoze.lru-0.4";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/r/repoze.lru/repoze.lru-0.4.tar.gz";
      md5 = "9f6ab7a4ff871ba795cadf56c20fb0f0";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  pastedeploy = buildPythonPackage rec {
    name = "PasteDeploy-1.5.0";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/P/PasteDeploy/PasteDeploy-1.5.0.tar.gz";
      md5 = "f1a068a0b680493b6eaff3dd7690690f";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  pyramid_jinja2 = buildPythonPackage rec {
    name = "pyramid_jinja2-1.3";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/pyramid_jinja2/pyramid_jinja2-1.3.tar.gz";
      md5 = "4081c4dfe3996b4ae5eb3843bcd4e4ca";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ jinja2 pyramid ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  docutils = buildPythonPackage rec {
    name = "docutils-0.9.1";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/docutils/docutils-0.9.1.tar.gz";
      md5 = "b0d5cd5298fedf9c62f5fd364a274d56";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  deform_bootstrap = buildPythonPackage rec {
    name = "deform_bootstrap-0.2.6";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/d/deform_bootstrap/deform_bootstrap-0.2.6.tar.gz";
      md5 = "10aa4f5fd37a126506dc179805e6b061";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ deform ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  pg8000 = buildPythonPackage rec {
    name = "pg8000-1.05";

    src = fetchurl {
      url = "http://pybrary.net/pg8000/dist/pg8000-1.08.tar.gz";
      md5 = "2e8317a22d0e09a6f12e98ddf3bb75fd";
    };

    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  webob = buildPythonPackage rec {
    name = "WebOb-1.2b3";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/W/WebOb/WebOb-1.2b3.zip";
      md5 = "e0cdf8657fd77b1da7c12bed838596ba";
    };

    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  pyramid_tm = buildPythonPackage rec {
    name = "pyramid_tm-0.3";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/pyramid_tm/pyramid_tm-0.3.tar.gz";
      md5 = "e54274f7b33614d7e0254f6c2c5ac206";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ transaction pyramid ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  zope_deprecation = buildPythonPackage rec {
    name = "zope.deprecation-3.5.0";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/z/zope.deprecation/zope.deprecation-3.5.0.tar.gz";
      md5 = "1e7db82583013127aab3e7e790b1f2b6";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ setuptools ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  chameleon = buildPythonPackage rec {
    name = "Chameleon-2.7.3";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/C/Chameleon/Chameleon-2.7.3.tar.gz";
      md5 = "c40243b8b68081ad6733673c02b65369";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  mysql_connector_repackaged = buildPythonPackage rec {
    name = "mysql-connector-repackaged-0.3.1";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/m/mysql-connector-repackaged/mysql-connector-repackaged-0.3.1.tar.gz";
      md5 = "0b17ad1cb3fe763fd44487cb97cf45b2";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  markupsafe = buildPythonPackage rec {
    name = "MarkupSafe-0.15";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.15.tar.gz";
      md5 = "4e7c4d965fe5e033fa2d7bb7746bb186";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  pytz = buildPythonPackage rec {
    name = "pytz-2013b";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/pytz/pytz-2013b.zip";
      md5 = "c70dc37ffe435dd77e3f967a0dffe928";
    };

    buildInputs = [ pkgs.unzip ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  jinja2 = buildPythonPackage rec {
    name = "Jinja2-2.6";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.6.tar.gz";
      md5 = "1c49a8825c993bfdcf55bb36897d28a2";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  peppercorn = buildPythonPackage rec {
    name = "peppercorn-0.4";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/peppercorn/peppercorn-0.4.tar.gz";
      md5 = "464d6f2342eaf704dfb52046c1f5c320";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  translationstring = buildPythonPackage rec {
    name = "translationstring-0.4";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/t/translationstring/translationstring-0.4.tar.gz";
      md5 = "392287923c475b660b7549b2c2f03dbc";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  beaker = buildPythonPackage rec {
    name = "Beaker-1.6.3";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/B/Beaker/Beaker-1.6.3.tar.gz";
      md5 = "bd4a986a3cad26d576e7ee77cce86b4f";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  transaction = buildPythonPackage rec {
    name = "transaction-1.1.1";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/t/transaction/transaction-1.1.1.tar.gz";
      md5 = "30b062baa34fe1521ad979fb088c8c55";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ zope_interface ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  zope_interface = buildPythonPackage rec {
    name = "zope.interface-3.8.0";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/z/zope.interface/zope.interface-3.8.0.tar.gz";
      md5 = "8ab837320b4532774c9c89f030d2a389";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ setuptools ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  webhelpers = buildPythonPackage rec {
    name = "WebHelpers-1.3";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/W/WebHelpers/WebHelpers-1.3.tar.gz";
      md5 = "32749ffadfc40fea51075a7def32588b";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ markupsafe ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  pyramid_beaker = buildPythonPackage rec {
    name = "pyramid_beaker-0.6.1";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/p/pyramid_beaker/pyramid_beaker-0.6.1.tar.gz";
      md5 = "8120e4cfbbf88408f17607e7ab89001e";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ beaker pyramid ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  colander = buildPythonPackage rec {
    name = "colander-0.9.6";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/c/colander/colander-0.9.6.tar.gz";
      md5 = "2d9f65a64cb6b7f35d6a0d7b607ce4c6";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ translationstring ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  venusian = buildPythonPackage rec {
    name = "venusian-1.0a3";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/v/venusian/venusian-1.0a3.tar.gz";
      md5 = "7e3a522772ed2c98e9922ade569c7474";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [  ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

  waitress = buildPythonPackage rec {
    name = "waitress-0.8.1";

    src = fetchurl {
      url = "http://pypi.python.org/packages/source/w/waitress/waitress-0.8.1.tar.gz";
      md5 = "aadfc692b780fc42eb05ac819102d336";
    };

    buildInputs = [  ];
    propagatedBuildInputs = [ setuptools ];
    doCheck = false;

    installCommand = ''
      easy_install --always-unzip --no-deps --prefix="$out" .
    '';

    meta = {
      maintainers = [
        stdenv.lib.maintainers.garbas
        stdenv.lib.maintainers.iElectric
      ];
      platforms = stdenv.lib.platforms.all;
    };
  };

}; in almir01Packages
