from typing import Union

class InvalidVersion(ValueError): ...

class Version:
    def __init__(self, version: str) -> None: ...

class LegacyVersion: ...

def parse(version: str) -> Union[Version, LegacyVersion]: ...
